Models/AddEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MSS.Models.Domain;

namespace MSS.Models
{
    public class AddEntryViewModel
    {
        public Guid ProductId { get; set; }

        public Guid SelectedProductId { get; set; }

        public int Quantity { get; set; }

        public DateTime Date { get; set; }
        
        public string Local { get; set; }
    }
}

Models/AddProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSS.Models
{
    public class AddProductViewModel
    {
        public string Name { get; set;}

        public string MadeBy { get; set;}

        public string Type { get; set;}

        public string Description { get; set;}
    }
}

Models/Domain/Entry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSS.Models.Domain
{
    public class Entry
    {
        public Guid ProductId { get; set; }

        public int Quantity { get; set; }

        public DateTime Date { get; set; }
        
        public string Local { get; set; }

    }
}

Models/Domain/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSS.Models.Domain
{
    public class Product
    {
        public Guid Id { get; set;}
        public string Name { get; set;}

        public string MadeBy { get; set;}

        public string Type { get; set;}

        public string Description { get; set;}
        
    }
}

Controllers/EntryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MSS.Data;
using MSS.Models;
using MSS.Models.Domain;

namespace MSS.Controllers
{
  [Route("[controller]")]
    public class EntryController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public EntryController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public async Task<IActionResult> Add()
        {
            var ProductList = await _appDbContext.Product.ToListAsync();
            ViewBag.ProductsList = new SelectList(ProductList, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEntryViewModel request)
        {
            var entry = new Entry()
            {
                ProductId = request.ProductId,
                Quantity = request.Quantity,
                Date = request.Date,
                Local = request.Local,
            };

            // await _appDbContext.Entry.AddAsync(entry);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MSS.Models;

namespace MSS.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSS.Data;
using MSS.Models;
using MSS.Models.Domain;

namespace MSS.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ProductController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddProductViewModel addProduct)
        {
            var product = new Product()
            {
                Id = Guid.NewGuid(),
                Name = addProduct.Name,
                MadeBy = addProduct.MadeBy,
                Type = addProduct.Type,
                Description = addProduct.Description
            };

            await _appDbContext.Product.AddAsync(product);
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var ProductList = await _appDbContext.Product.ToListAsync();
            return View(ProductList);
        }
    }
}

Views/Entry/Add.cshtml
@model MSS.Models.AddEntryViewModel

<div class="text-left">
    <h1 class="display-4 mb-3">Adicionar Entrada:</h1>
    <form method="post" asp-action="Add" asp-controller="Entry">
        <div class="mb-3">
        <label for="productName" class="form-label">Selecione o produto:</label>
        <select name="" id="" asp-for="SelectedProductId" asp-items="ViewBag.ProductsList"></select>
    </div>
        <div class="mb-3">
            <label for="MadeBy" class="form-label">Quantidade:</label>
            <input type="number" class="form-control" id="MadeBy" aria-describedby="MadeBy" asp-for="Quantity" required>
        </div>
        <div class="mb-3">
            <label for="Type" class="form-label">Data:</label>
            <input type="datetime-local" class="form-control" id="Type" aria-describedby="Type" asp-for="Date" required>
        </div>
        <div class="mb-3">
            <label for="Description" class="form-label">Local:</label>
            <input type="text" class="form-control" id="Description" aria-describedby="Description" asp-for="Local" required>
        </div>
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Sistema de Gestão</h1>
</div>

Views/Product/Add.cshtml
@model MSS.Models.AddProductViewModel

<div class="text-left">
    <h1 class="display-4 mb-3">Adicionar Produto</h1>
    <form method="post" asp-action="Add" asp-controller="Product">
        <div class="mb-3">
            <label for="productName" class="form-label">Insira o nome do produto:</label>
            <input type="text" class="form-control" id="productName" aria-describedby="productName" asp-for="Name" required>
        </div>
        <div class="mb-3">
            <label for="MadeBy" class="form-label">Feito por:</label>
            <input type="text" class="form-control" id="MadeBy" aria-describedby="MadeBy" asp-for="MadeBy" required>
        </div>
        <div class="mb-3">
            <label for="Type" class="form-label">Tipo:</label>
            <input type="text" class="form-control" id="Type" aria-describedby="Type" asp-for="Type" required>
        </div>
        <div class="mb-3">
            <label for="Description" class="form-label">Descrição do produto:</label>
            <input type="text" class="form-control" id="Description" aria-describedby="Description" asp-for="Description" required>
        </div>
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>
</div>

Views/Product/Index.cshtml
@model List<MSS.Models.Domain.Product>

<h1>Product</h1>
  @foreach (var product in Model)
  {
    <p>@product.Name</p> 
  }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MSSuply</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MSS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MSS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entry" asp-action="Add">Adicionar Entrada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Add">Adicionar Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Por: Alan Sá
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>